### ISSUE TITLE
Local ODC-colab

### ISSUE THREAD

**Issue by sebfoe** [ceos-seo/odc-colab#2]
Hello all,
I want to use the the ODC-colab realization on my local machine.
1.) I have set up an conda root-environment
2.) I ran a notebook:
  i.) `!wget -nc https://raw.githubusercontent.com/ceos-seo/odc-colab/master/odc_colab.py`
  ii.) `kwargs={"DATACUBE_DB_URL":'postgresql://<USER>:<PASSWORD>@<HOST>:<PORT>/datacube'}
odc_colab_init(**kwargs)`
  iii.) I downloaded the db_dump to my machine and `populate_db('/path/to/tar/')`; all &&PATH&& variables inside the zipped dump, i.e. the `restore.sql` are changed to point the unzipped dat-files, like /path/to/db_dump/3003.dat; this gives me `Lockfile exists, skipping population.`

 vi.) the code-block 
#### Suppress Warning Messages
import warnings
warnings.filterwarnings('ignore')

#### Load Data Cube Configuration
from odcgee.odc_gee import earthengine
dc = earthengine.Datacube(app='App')

#### Import Data Cube API
import utils.data_cube_utilities.data_access_api as dc_api  
api = dc_api.DataAccessApi()

##### Import Utilities
import xarray as xr`

  works, with this warning: `DeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
  username=username, password=password,`

 v.) Applying `products = dc.list_products()` gives me an empty list 

I had erased the `if install_postgresql` sequence (odc_colab.py), because otherwise, `odc_colab_init` gives me '['sudo', '-u', 'postgres', 'createuser', '-s', 'root']' returned non-zero exit status 1, after inserting the root password.

Maybe I am totally wrong, I am a geographer...
I would very appreciate your ideas or solutions for this problem, thank you!

Best
Sebastian

**Comment by dlubawy-ama** [comment]
Hi Sebastian,
Thanks for taking an interest in the project and submitting an issue. Unfortunately, unless I'm mistaken by your meaning of local machine, it seems that you may be trying to do something which isn't supported by this project. Are you trying to run the `odc_colab.py` script and setup an environment using our tools on a local machine that isn't in a Colab VM?

**Comment by sebfoe** [comment]
Hi Andrew,
thank you very much for your reply. Yes, I have tried it on my local machine, not a  Colab VM.
Obviously totally misunderstood, the essential part of reading data failed.
First tests on a Colab VM seems to work pretty well, further will follow.

Thank you for starting this project, very interesting!

**Comment by dlubawy-ama** [comment]
Sorry for the misunderstanding. This project is strictly for use within Google Colab. We will update our README to clarify this and further specify the terminology there such as any mentions to 'local database' meaning local to the Colab VM. Hopefully that will help with any confusion for other users, so thank you for bringing this to our attention.

If you _would_ like to run Open Data Cube (ODC) on a local machine then I encourage you to check out [the ODC's installation page](https://www.opendatacube.org/installation) for further information.

If familiar with ODC usage and you are looking to use Google Earth Engine with it then we have [that in another project](https://github.com/ceos-seo/odc-gee).

I'll close this issue since it is out of scope and seems resolved now, but if you do find any other issues in your tests within Colab then please feel free to open a new issue on GitHub for us to look at.
